
services:
  chat-backend:
    restart: always
    container_name: chat-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8006:80"
    env_file:
      - .env
    volumes:
      - .:/backend
      - ./static:/backend/static
      - ./media:/backend/media

  chat-redis:
    container_name: chat-redis
    restart: always
    image: redis:7.0.15
    hostname: redis-db
    ports:
      - "127.0.0.1:6381:6379"

  chat-database:
    restart: always
    container_name: chat-database
    image: postgres:17.5
    hostname: meetandchat
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_USER=$PGUSER
      - POSTGRES_DB=$PGDATABASE

volumes:
  postgres_data: