# Generated by Django 5.2.1 on 2025-05-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_n_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatqueue',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voicechatqueue',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
