# Generated by Django 5.2.1 on 2025-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_n_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatqueue',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
