# Generated by Django 5.2.1 on 2025-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_n_chat', '0002_alter_chatqueue_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatqueue',
            name='user_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
