# Generated by Django 5.2.1 on 2025-05-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_n_chat', '0003_chatqueue_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatqueue',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chatqueue',
            name='user_id',
            field=models.UUIDField(unique=True),
        ),
    ]
