# Generated by Django 5.2.1 on 2025-05-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_n_chat', '0005_voicechatqueue_alter_chatqueue_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicechatqueue',
            name='username',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
    ]
