# Generated by Django 5.2.1 on 2025-05-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_n_chat', '0006_voicechatqueue_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatqueue',
            name='username',
            field=models.CharField(default='er', max_length=100),
            preserve_default=False,
        ),
    ]
