# Generated by Django 5.2.1 on 2025-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_n_chat', '0008_chatqueue_chat_color_voicechatqueue_chat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatqueue',
            name='channel_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voicechatqueue',
            name='channel_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatqueue',
            name='username',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='voicechatqueue',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
